@Api_HostAddress = http://localhost:5241

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json



###
GET {{Api_HostAddress}}/api/Cathi/
Accept: application/json
###
GET {{Api_HostAddress}}/api/ThongTinSinhVien/
Accept: application/json

###
GET {{Api_HostAddress}}/api/ThongTinSinhVien/1048251970
Accept: application/json